version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

aliases:
  - &docker
    - image: node:12-buster-slim

  - &restore_yarn_cache
    restore_cache:
      name: Restore Yarn cache
      keys:
        - yarn-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-v2-{{ .Branch }}
        - yarn-v2-master
  
  - &save_yarn_cache
    save_cache:
      name: Save Yarn cache
      key: yarn-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
        - /usr/local/share/.cache/yarn

  - &yarn_install
    run:
      name: Install Node modules
      command: yarn --frozen-lockfile

jobs:
  build:
    docker: *docker

    steps:
      - checkout

      - run:
          name: Node.js version
          command: |
            node --version
            npm --version
            yarn --version
      - *restore_yarn_cache
      - *yarn_install
      - *save_yarn_cache
      - run:
          name: Setup
          command: |
            ARTIFACTS="$(pwd)/artifacts"
            echo "export ARTIFACTS=\"${ARTIFACTS}\"" >> $BASH_ENV
            mkdir -p $ARTIFACTS

      - run:
          name: ESLint
          command: |
            cd packages/undercut
            yarn lint --format="junit" --output-file="eslint.xml"
            mkdir -p $ARTIFACTS/test_results/eslint
            cp -v eslint.xml $ARTIFACTS/test_results/eslint/
      - run:
          name: Jest
          command: |
            cd packages/undercut
            yarn test --ci --coverage --reporters="default" --reporters="jest-junit" --runInBand
            cp -v coverage/clover.xml $ARTIFACTS/coverage.xml
            mkdir -p $ARTIFACTS/test_results/jest
            cp -v jest.xml $ARTIFACTS/test_results/jest/
          environment:
            JEST_JUNIT_OUTPUT_NAME: jest.xml
      - run:
          name: Package
          command: |
            cd packages/undercut
            npm pack
            cp -v undercut-*.tgz $ARTIFACTS/

      - store_artifacts:
          path: artifacts
      - store_test_results:
          path: artifacts/test_results
      - codecov/upload:
          file: artifacts/coverage.xml
